### ISSUE TITLE
RNCryptor - decryption is failing in Swift

### ISSUE THREAD

**Issue by ReddySanthosh** [RNCryptor/RNCryptor#246]
When I try to decrypt the encrypted data, decryption is not happening its throwing error, but could capture the error as it is not happening every time.

Below is the code for decryption.

// Fetching the stored "Encrypted Data" from User defaults
        let defaults = UserDefaults.standard
        if let cipherData = defaults.object(forKey: "cipherData"){

        let password = "AaBbCc"

       let decryptedString = RNCryptor.decrypt(data: dataToDecrypt, withPassword: password)

Would like to know what would caused this.

**Comment by rnapier** [comment]
The above code is trying to decrypt a `String`; the first parameter of `decrypt()` is a `Data`. Without knowing what data you're passing or what error you're receiving, or at least the actual code you're using, I can't help you.

**Comment by ReddySanthosh** [comment]
Sorry for the incomplete code, I have corrected it. Kindly help.
Was not able to capture the error.

**Comment by rnapier** [comment]
If this happened only once, that strongly suggests that the user defaults value was just empty or corrupted. I would expect that you got to a place in the code where you read the value without actually having written it or having written it incorrectly. 

As written I assume the above code still can't compile. cipherData looks to be of type Any. But I assume you convert it to Data at some point. If you converted with "as! Data" then it would have crashed your program.
